const data = {
    "sku": "171671",
    "offer_id": "1002287",
    "offer_name": "ДАКОТА, венге цаво/дуб молочный с рисунком, норма",
    "offer_section_name": {
        "2594": {
            "ID": "2594",
            "TIMESTAMP_X": "22.06.2023 16:00:59",
            "MODIFIED_BY": "0",
            "DATE_CREATE": "03.10.2018 12:30:03",
            "CREATED_BY": "0",
            "IBLOCK_ID": "1",
            "IBLOCK_SECTION_ID": "2929",
            "ACTIVE": "Y",
            "GLOBAL_ACTIVE": "Y",
            "SORT": "500",
            "NAME": "Стенки и горки комплектные",
            "PICTURE": "1955458",
            "LEFT_MARGIN": "147",
            "RIGHT_MARGIN": "148",
            "DEPTH_LEVEL": "3",
            "DESCRIPTION": "",
            "DESCRIPTION_TYPE": "text",
            "SEARCHABLE_CONTENT": "СТЕНКИ И ГОРКИ КОМПЛЕКТНЫЕ\r\n",
            "CODE": "stenki_i_gorki_komplektnye",
            "XML_ID": "e04cb933-c6a8-11e8-a346-6c92bf0ba201",
            "TMP_ID": null,
            "DETAIL_PICTURE": null,
            "SOCNET_GROUP_ID": null,
            "LIST_PAGE_URL": "#SITE_DIR#/catalog/",
            "SECTION_PAGE_URL": "#SITE_DIR#/catalog/#SECTION_CODE#/",
            "IBLOCK_TYPE_ID": "catalogs",
            "IBLOCK_CODE": "catalog",
            "IBLOCK_EXTERNAL_ID": "1",
            "EXTERNAL_ID": "e04cb933-c6a8-11e8-a346-6c92bf0ba201",
            "UF_CREDIT_ID": null,
            "UF_VIRTUAL": "0",
            "UF_LINKED_SECTIONS": [],
            "UF_BOTTOMTEXT": "<p>Гостиную без стенки сегодня невозможно представить. Как правило, она выполняет эстетическую и практическую роль, придавая комнате уют и функциональность, обеспечивая место хранение для книг, посуды и прочих вещей. Современная стенка в гостиную отличается стильным дизайном, компактностью и практичностью. Такой предмет интерьера поможет выделить различные зоны самой центральной комнаты в вашем доме.</p>\r\n<h2>Какие бывают, что лучше выбрать</h2>\r\n<p>Различают несколько вариантов стенок в гостиную:</p>\r\n<ol>\r\n\t<li>Фронтальная модель. Все модули ставятся вдоль одной стены, закрывая ее полностью или частично.</li>\r\n\t<li>Угловой вариант. В таких комплектах можно использовать глубину угла &ndash; отличное решение для тех, кому нужно много пространства для хранения вещей. Так что массивность мебели не станет проблемой даже для малогабаритной комнаты.</li>\r\n\t<li>Подвесная модель. Некоторые части конструкции закрепляются на стенах, но это ограничит ее габариты и функциональность.</li>\r\n</ol>\r\n<p>Размер стенки в гостиную зависит от площади помещения. Чем она больше, тем более габаритную мебель можно выбрать. Однако, помните, что современные интерьеры отличаются минимализмом. Поэтому несколько навесных полок, тумба под ТВ или небольших шкафов станут оригинальным акцентом и позволят удобно разместить все необходимые вещи.</p>\r\n<p>В случае если вопрос экономии пространства стоит во главе угла, модульная стенка станет отличным решением. Пожалуй, это настоящая находка для малогабаритных квартир. Чтобы визуально расширить пространство, выбирайте мебельный гарнитур с глянцевыми фасадами. Такая модель хорошо гармонирует с интерьерами в стиле модерн и хай-тек.</p>\r\n<h2>Стенки в гостиную от &laquo;Азбука мебели&raquo;</h2>\r\n<p>В нашем интернет-магазине можно выбрать и купить стенку в гостиную по низкой цене от ведущих мировых производителей. Пожалуй, это лучший выбор для тех, кто знает толк в высококачественной мебели.</p>\r\n<p>Все мебельные гарнитуры, представленные в каталоге в обширном ассортименте, &ndash; это:</p>\r\n<ul>\r\n\t<li>стильный дизайн;</li>\r\n\t<li>многофункциональность;</li>\r\n\t<li>большое многообразие моделей на любой вкус;</li>\r\n\t<li>прочность и долговечность;</li>\r\n\t<li>безупречное качество материалов и надежная фурнитура;</li>\r\n\t<li>удобство использования.</li>\r\n</ul>\r\n<p>Если вы сомневаетесь, можно ли сегодня приобрести качественную мебель недорого, &ndash; загляните в наш каталог. Мы работаем с мебельными фабриками напрямую, что позволяет поставлять изделия отличного качества, с гарантией и по адекватной стоимости. Вся мебель есть в наличии на нашем складе. Доставка производится в четко оговоренные сроки. Удачного выбора и приятных покупок.</p>\r\n",
            "UF_DISCOUNT": null,
            "UF_RELATED_SECTIONS": [
                2474,
                2506,
                2495,
                2485,
                2489,
                2508
            ],
            "UF_SALE_FROM_MART": "0",
            "UF_IS_HIDDEN": "0",
            "UF_CAN_SELL_HOME_PRODUCTS": "0",
            "UF_OZON_SECTION_CODE": [
                "52669267"
            ],
            "UF_SEO_TITLE": "Стенки для гостиной купить во Владивостоке по низкой цене",
            "UF_SEO_DESCR": "Стенки для гостиной с гарантией от производителя. Широкий ассортимент мебели для гостиной по выгодной цене. Доставка по Владивостоку и России.",
            "UF_SEO_H1": "Стенки для гостиной",
            "UF_URL": "stenki-i-gorki-komplektnye",
            "UF_CODE_1C": "0000557"
        },
        "2639": {
            "ID": "2639",
            "TIMESTAMP_X": "22.06.2023 16:00:56",
            "MODIFIED_BY": "0",
            "DATE_CREATE": "13.12.2019 11:30:03",
            "CREATED_BY": "0",
            "IBLOCK_ID": "1",
            "IBLOCK_SECTION_ID": "2635",
            "ACTIVE": "Y",
            "GLOBAL_ACTIVE": "Y",
            "SORT": "500",
            "NAME": "Комплектные стенки и горки",
            "PICTURE": null,
            "LEFT_MARGIN": "235",
            "RIGHT_MARGIN": "236",
            "DEPTH_LEVEL": "3",
            "DESCRIPTION": "",
            "DESCRIPTION_TYPE": "text",
            "SEARCHABLE_CONTENT": "КОМПЛЕКТНЫЕ СТЕНКИ И ГОРКИ\r\n",
            "CODE": "komplektnye_stenki_i_gorki",
            "XML_ID": "836c6796-1d42-11ea-be1a-6c92bf0ba200",
            "TMP_ID": null,
            "DETAIL_PICTURE": null,
            "SOCNET_GROUP_ID": null,
            "LIST_PAGE_URL": "#SITE_DIR#/catalog/",
            "SECTION_PAGE_URL": "#SITE_DIR#/catalog/#SECTION_CODE#/",
            "IBLOCK_TYPE_ID": "catalogs",
            "IBLOCK_CODE": "catalog",
            "IBLOCK_EXTERNAL_ID": "1",
            "EXTERNAL_ID": "836c6796-1d42-11ea-be1a-6c92bf0ba200",
            "UF_CREDIT_ID": null,
            "UF_VIRTUAL": "0",
            "UF_LINKED_SECTIONS": [],
            "UF_BOTTOMTEXT": null,
            "UF_DISCOUNT": null,
            "UF_RELATED_SECTIONS": [],
            "UF_SALE_FROM_MART": "0",
            "UF_IS_HIDDEN": "0",
            "UF_CAN_SELL_HOME_PRODUCTS": null,
            "UF_OZON_SECTION_CODE": false,
            "UF_SEO_TITLE": null,
            "UF_SEO_DESCR": null,
            "UF_SEO_H1": null,
            "UF_URL": null,
            "UF_CODE_1C": "0000725"
        }
    },
    "detail_page_url": "/catalog/stenki_i_gorki_komplektnye/1002255/?offerId=1002287",
    "common_images": [
        "/upload/uf/642/642312a3e45b570de53167451ca4dd14.jpg",
        "/upload/uf/153/wcqjy5mhrsqg5uavqalyd9wycfvlokgk.jpg",
        "/upload/uf/83e/h1ywxvxerv7oa47uv34yacu0dbfpsgzw.jpg"
    ],
    "marketplace_images": [],
    "live_images": [
        "/upload/uf/dd5/u42kj3csd1ev2rt8wfn7nr10fcn97ko4.jpg",
        "/upload/uf/aea/ujr83qn3sabh5y14cayd7n39l2ummfss.jpg",
        "/upload/uf/db8/06kcjyjo14uj13dtis3fefa1izz9077b.jpg",
        "/upload/uf/e00/0vmiyha4j6cprgf1zmq9us5skwpp5qc0.jpg",
        "/upload/uf/066/gbrka68w7hln2uprvrlew7vz5s40jq5x.jpg",
        "/upload/uf/7ff/fmhwirb3jyek09ae9lc1gao7ft0zd8ae.jpg",
        "/upload/uf/932/831b0lt9zvycesuko7a380c7mwfhb3l7.jpg"
    ],
    "video": [],
    "display_properties": [
        {
            "CODE": "24153",
            "NAME": "Размер ниши под ТВ (мм)",
            "VALUE": "1100 х 916",
            "DESCRIPTION": null,
            "XML_ID": "480a56b2-8790-11e5-b612-001e67218051",
            "PROPERTY_TYPE": "S"
        },
        {
            "CODE": "MLENGTH",
            "NAME": "Длина",
            "VALUE": "2364",
            "DESCRIPTION": null,
            "XML_ID": "f3b4ffd9-2699-11e5-8b70-001e67218051",
            "PROPERTY_TYPE": "N"
        },
        {
            "CODE": "24170",
            "NAME": "Глубина",
            "VALUE": "362",
            "DESCRIPTION": null,
            "XML_ID": "f3b4ffdb-2699-11e5-8b70-001e67218051",
            "PROPERTY_TYPE": "N"
        },
        {
            "CODE": "24171",
            "NAME": "Высота",
            "VALUE": "1872",
            "DESCRIPTION": null,
            "XML_ID": "f3b4ffdc-2699-11e5-8b70-001e67218051",
            "PROPERTY_TYPE": "N"
        },
        {
            "CODE": "STYLE",
            "NAME": "Стиль",
            "VALUE": "Современный",
            "DESCRIPTION": null,
            "XML_ID": "f3b4fff3-2699-11e5-8b70-001e67218051",
            "PROPERTY_TYPE": "S"
        },
        {
            "CODE": "24236",
            "NAME": "Материал корпуса",
            "VALUE": "ЛДСП",
            "DESCRIPTION": null,
            "XML_ID": "f3b5001d-2699-11e5-8b70-001e67218051",
            "PROPERTY_TYPE": "S"
        },
        {
            "CODE": "24237",
            "NAME": "Материал фасада",
            "VALUE": "ЛДСП",
            "DESCRIPTION": null,
            "XML_ID": "f3b5001e-2699-11e5-8b70-001e67218051",
            "PROPERTY_TYPE": "S"
        },
        {
            "CODE": "24725",
            "NAME": "Гарантия",
            "VALUE": "24 мес.",
            "DESCRIPTION": null,
            "XML_ID": "067ab7e2-393f-11e8-afb3-001e67218051",
            "PROPERTY_TYPE": "S"
        },
        {
            "CODE": "24753",
            "NAME": "Место производства",
            "VALUE": "г. Волгодонск",
            "DESCRIPTION": null,
            "XML_ID": "0d21afec-993f-11e8-9fab-001e67218051",
            "PROPERTY_TYPE": "S"
        },
        {
            "CODE": "WEIGHT",
            "NAME": "Вес",
            "VALUE": "132",
            "DESCRIPTION": null,
            "XML_ID": "aa468be6-4e8c-11e9-b0ae-6c92bf0ba201",
            "PROPERTY_TYPE": "S"
        }
    ]
}